var lvl1 = ["Some spent only a short time in foster care before being reunited with their biological family.  Others will stay in the system for years to come.  It's difficult to obtain accurate information about foster care kids' experiences from any given state, and some states don't even report in.  The good news is according to available stats, the number of kids in the system increased during the 1990s before dropping to a historic low in 2012.  The bad news?  We're back on the rise, with over 10,000 more kids in foster care in 2016 than 2015, and in 2016 there were 23,291 more children entering than exiting foster care. ",
"In 2016, over 20.000 foster children “aged out” of the system, meaning they reached the age of 18 without being adopted or reunited with their biological families.",
"Of the 15 categories states can report for circumstances associated with a child's placement in foster care, drug abuse also had the highest increase.  ",
"Of the 15 categories states can report for circumstances associated with a child's placement in foster care, drug abuse also had the highest increase."
];
var lvl2 = ["Approximately 687,000 children spent time in the foster care system in 2016, according to the U.S. Department of Health and Human Services.  Some of those children spent only a short time in foster care before being reunited with their biological family.  Others will stay in the system for years to come.",
"Nationally, the average time spent in foster care is approximately two years, with 15% of foster children staying in the system for three years or more.  In 2016, over 20.000 foster children “aged out” of the system, meaning they reached the age of 18 without being adopted or reunited with their biological families.",
"The average age of kids entering the U.S. foster care system is 7.  However, that number is trending downward due to the influx of children who have been removed from their biological parents due to the opioid epidemic.  The average age of kids removed from their parents due to drug abuse in 2016 was 4 years younger than other kids in foster care.",
"Since 2009, the percentage of children who leave care to adoption has remained steady at about 21 to 23 percent of all foster care exits. Of the 402,378 U.S. children in foster care now, it's estimated that 101,840 are eligible for adoption. The number of waiting children has equaled about 26 to 27 percent of children in care for many years.  Almost two-thirds of these eligible children will eventually be adopted into forever families. However, this means that about 20,000 kids who could have been adopted will age out of foster care without ever being placed with a permanent family."
];
var lvl3 = ["55% of foster children have reunification with their biological parents as their goal. Even though typically they have been removed from their parents due to neglect or abuse, a majority of foster children want to be returned to their biological families when that is possible. For the first time, following passage of The Family First Act in March, 2018, the first major piece of legislation on foster care to be passed in the last 50 years, the federal government will start reimbursing states for expenses involved with reunifying families, and for program costs associated with preventing children from being removed from their biological parents in the first place. ",
"Research indicates that as many as 40% of children placed in foster care will end up separated from one or all of their siblings. (Seattle Journal for Social Justice, Volume 12, Issue 2, 2013). Despite the 2008 passage of the federal Fostering Connections Act, which mandated that siblings in foster care should be placed together whenever possible, and laws aimed at keep siblings together in more than half of U.S. states, in practice siblings are still often separated while in foster care.   Being separated from their siblings is an additional loss to being separated from their parents, and for many foster children, is an even bigger source of trauma.",
"Playdates, sleepovers and field trips are a normal part of childhood for most kids.  But prior to 2014, many foster children didn’t get to experience such events, due to the legal liability foster parents faced if something went wrong on a sleepover or trip they approved. But since passage of the federal “Preventing Sex Trafficking and Strengthening Families Act” in 2014, foster parents have had more latitude to make such choices on behalf of their foster kids. The law required states to implement a “reasonable and prudent parenting standard” giving foster parents the authority to make day-to-day decisions affecting children in their care regarding extracurricular, enrichment, cultural, social or sporting activities.  So foster kids now get to have a more normal childhood, which is win for them, and a win for their foster parents. (AP News, Dec., 2017)",
"On average, students in foster care move schools at least once or twice a year, and by the time they age out of the system, over one third will have experienced five or more school moves.  Children are estimated to lose four to six months of academic progress per move, which puts most foster care children years behind their peers. School transfers also decrease the chances a foster care student will ever graduate from high school. A national study of 1,087 foster care alumni found that “youth who had even one fewer change in living arrangement per year were almost twice as likely to graduate from high school before leaving foster care.” (The Atlantic, 2/28/14)"];
var lvl4 = ["Reimbursement levels vary widely state to state, and also by the age and needs of the child.  But on average, foster parents receive between $20 and $25 per day for taking care of a child. This amounts to between $650 to $800 per month, or around $9000 per year. Despite a persistent myth that many foster parents, “Do it for the money,” this typically amounts to approximately $1 per hour, per child, per day (ChildTrends.org).",
"Combined state-local-federal spending on the foster care system totals approximately $29B per year.  This amounts to approximately $62,100 per foster child, per year.  As noted above, foster parents themselves receive only $9000 per year, per child, on average.  So the vast majority of the money being spent on our nation’s foster children is on administration of the system, higher cost residential care for some youth, medical services and other costs.  The money is not going directly to foster parents.",
"The average middle income family now spends over $231,000 to raise a child to the age of 18, or approximately $13,500 per year. On average, upper income families (over $110K in income per year) spend approximately $372,000 ($21,000 per year).  Lower income families spend approximately $175,000, or $9700 per year (TIME magazine).  Foster parents therefore receive less per year than what average, lower income families spend on their children.",
"Foster children “age out” of the foster care system when they turn 18.  However, since 2008 states have the option to continue providing support to foster children up to the age of 19, 20 or 21 if the youth is: completing secondary education; enrolled in an institution which provides vocational education; participating in a program to find employment; or employed for at least 80 hours per month."];
var lvl5 = ["25% of all foster children who age out of the system will be arrested and spend at least one night in jail within the first two years. An eight year study by the University of Chicago showed that 60 percent of males who spent time in foster care were convicted of a crime by age 24, and more than 80 percent had been arrested. Nationally, over 40% of former foster youth will be arrested at least once, compared to only 14% of the regular population (Doyle study, MIT, 2007). Significantly, foster youth placed in group home settings are 2.5 times more likely to become involved with the juvenile justice system, compared to foster youth who are placed with stable foster families (JP Ryan, Children and Youth Services Review, 2008).",
"58% of foster children will graduate from high school by age 19, compared to 87% of all 19-year-olds. (“Outcomes At Age 19,” 2005 study, Chapin Hall Center for Children at the University of Chicago). Additionally, more than one in five foster youth who age out will become homeless after age 18, a huge contributor to the growing number of people living on the street in the United States (“Outcomes At Age 19,” 2005 study, University of Chicago).",
"Fewer than 3 percent of foster youth will earn a college degree by age 25 (compared to 28 percent of all 25-year-olds).  And by age 24, only 50% of former foster children will be employed.  On average, for every young person who ages out of foster care, taxpayers and communities pay $300,000 in social costs like public assistance, incarceration, and lost wages over that person’s lifetime. This amounts to over $8 billion in social costs to the United States every year (Jim Casey Youth Opportunities Initiative Study, 2013) ",
"More than 50% of girls in the foster care system will become pregnant by the age of 19, compared to only 20% of teen girls nationally. And 71% of women who were formerly in foster care will become pregnant by the age of 21, compared to less than 40% of women who spent no time in foster care (Children’s Bureau, Administration on Children, Youth and Families).  Similarly, 50% of boys in foster care had gotten a partner pregnant while still a teenager, compared to 19% of boys in the general population (State of Utah, Dept. of Human Services)."];
var lvl6 = ["In most states, 100% tuition fee waivers are available for former foster children to attend state and local colleges.  If a child in foster care wants to go to college, grants and financial aid is available to make this possible.  However, in spite of such federal and state support programs, only about 30% of foster children finish high school, fewer than 11% ultimately attend college, and only 2.5% will attain a college degree (Casey Family Programs study).",
"The Family First Law, the first major piece of foster care legislation to be passed by Congress in 50 years, signified a major shift in federal policy towards foster children.  Rather than only reimbursing states for the costs of placing children in foster care or group homes (thereby incentivizing states to remove children from their biological parents) states will now also be given federal monies to help prevent parental abuse and neglect, with the goal of keeping more families together - addiction treatment, mental health counseling, parenting training, etc.",
"At least half of the states in the country have lost foster care capacity in the past five years, as the number of foster children needing placement went up.  Another 15 states were not able to provide enough information to even make a determination of their capacity. Meanwhile, only three states gained more foster homes during the same period against the backdrop of a lower, or even constant, number of youth in foster care. (The Chronicle of Social Change)",
"Between 30% and 50% of foster parents do not renew their foster care licenses each year, with more than half of new foster parents opting out after their first year.  But in many states, the numbers are even worse.  In 2015, Idaho licensed 352 new foster parents statewide, but saw a net increase of only 33 by 2016.  That means for every 11 new parents they licensed, only 1 remained a year later (2017 Report, Office of Performance Evaluations, Idaho State Legislature). Per survey, most parents who stop fostering do so after adopting their former foster children - they don’t want to take on more kids after that.  But a high percentage also let their foster licenses lapse due to “burnout” - they’re exhausted, and just can’t keep up with the demands of fostering.  (“Voluntary Closure Study - Former Foster Care Families,” Arizona State University School of Social Work, 2014)"
];
var explanationarr = [lvl1, lvl2, lvl3, lvl4, lvl5, lvl6];

function getCookie(cname) {
    var name = cname + "=";
    var ca = document.cookie.split(';');
    for(var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}

window.onload = function(){
    var lvlstr = getCookie("level");
    var qstr = getCookie("question");
    var lvl = 1;
    var q = 1;
    if (lvlstr != "") lvl = parseInt(lvlstr);
    if (qstr != "") q = parseInt(qstr);
    console.log(lvl);
    console.log(q);
    
    document.getElementById("explanationID").innerHTML = explanationarr[lvl][q];
}


